jobs: 
  publish: 
    name: Publish
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout repository"
        uses: actions/checkout@v2
      - 
        name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with: 
          distribution: adopt
          java-version: "11"
      - 
        name: "Grant Permission to Execute Gradle"
        run: "chmod +x gradlew"
      - 
        name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: build
      - 
        env: 
          ORG_GRADLE_PROJECT_VERSION_NAME: "${{ github.event.inputs.versionName }}"
          ORG_GRADLE_PROJECT_mavenCentralPassword: "${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
          ORG_GRADLE_PROJECT_mavenCentralUsername: "${{ secrets.MAVEN_CENTRAL_USERNAME }}"
          ORG_GRADLE_PROJECT_signingInMemoryKey: "${{ secrets.GPG_KEY }}"
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: "${{ secrets.GPG_PASSWORD }}"
        name: "Publish Library"
        run: |
            ./gradlew publish --no-daemon --no-parallel
            ./gradlew closeAndReleaseRepository
      - 
        env: 
          TAG: "${{ github.event.inputs.versionName }}"
        name: "Create and push tag"
        run: |
            git config --global user.email "primocaleb@gmail.com"
            git config --global user.name "$CodeCLS"
            git tag -a $TAG -m "Release v$TAG"
            git push origin $TAG
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: create_release
        name: "Create Release on GitHub"
        uses: actions/create-release@v1
        with: 
          draft: true
          prerelease: false
          release_name: "MyLib ${{ github.event.inputs.versionName }}"
          tag_name: "${{ github.event.inputs.versionName }}"
name: Publish
on:
  workflow_dispatch:
    inputs: 
      versionName: 
        description: "Version Name"
        required: true
